[versions]
coroutines = "1.5.0"
junit = "4.13.2"
mockk = "1.11.0"
robolectric = "4.5.1"
strikt = "0.31.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
strikt-core = { module = "io.strikt:strikt-core", version.ref = "strikt" }
strikt-mockk = { module = "io.strikt:strikt-mockk", version.ref = "strikt" }
