name: Quality Checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'changelogs/**'
      - '**.md'
      - '.github/*.yml'

jobs:
  assemble:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Build
        run: bash ./gradlew build --stacktrace

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
      - name: Unit tests
        run: bash ./gradlew :migration-core:check --stacktrace

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Run ktlint
        uses: le0nidas/ktlint-pr-comments@v1.2
        with:
          repotoken: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
